### ISSUE TITLE
is there a training code?

### ISSUE THREAD

**Issue by kimsekeun** [riponazad/echotracker#2]
Could you guys provide training code for reproducibility? 

Thanks.

**Comment by riponazad** [comment]
Hi @kimsekeun,

The training code is already there as a method in the class [def train](https://github.com/riponazad/echotracker/blob/main/model/net.py). Since we couldn't publish our dataset, we didn't explicitly show how to call the method. The following lines can be adapted to load your data and train/finetune EchoTracker.


```
from model.net import EchoTracker
B=1, # batchsize 
S=24, # seqlen
#you should have your own load_datasets() method before executing the following line    
dataloaders, dataset_size = load_datasets(B=B, S=S, debug=debug, use_aug=True)

model = EchoTracker(device_ids=[0])
#model.load(path=configs.WEIGHTS_PATH.echopips, eval=False)  #uncomment to fine-tune the model instead training
model.load(eval=False) #load the model to train
model.train(
        dataloaders=dataloaders, 
        dataset_size=dataset_size, 
        log_dir=configs.LOG_PATH.echotracker, 
        ckpt_path=configs.SAVE_PATH.echotracker,
        epochs=100
)
``` 

Please let me know if you need any further information.

Best,
Azad
